### ISSUE TITLE
Post-PA 2019

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#425]
Some issues came up during the PA 2019 update, a lot of light was shone on some old rotten code. Had to monkey patch over some rough stuff to get it out the door, but need to deal with these larger problems ASAP.

  - [x] get the `drr_planned_actual` panel working again, strip all reference to/reliance on the DRR from it. It moves forward with public accounts, not with DRRs: #430
  - [x] sort out years for DRRs/DPs, it's a mess. ~This might turn in to re-thinking how years work, as the current relative year templates are starting to feel like a fragile kludge (in places)~ Going to try and limit the scope of that #435
  - [x] roll the tag explorer actual resources tab forward #446
  - [x] ~coordinate with the pipeline on dropping tags to old policy programs~ can sleep on this, dropping the old policy programs might be put off until after DPs

**Comment by rossbm** [comment]
Not certain if this is the right place, but for all these programs were we have just one year of data, we are showing "0 year" ago on the welcome mat when it would be good to display "Last year" instead. I guess it is preferring to show whatever the latest historical is instead of the latest year.

**Comment by Stephen-ONeil** [comment]
I'll look in to that too, thanks!

**Comment by Stephen-ONeil** [comment]
Welcome Mat text issues uncovered by this update should be addressed by #431
