### ISSUE TITLE
Post-release covid estimates panel TODOs

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#838]
Rushed out to hit the deadline, lots of stuff between the API and client to polish off as things settle. Some changes may or may not be better to leave off pending changes to the form of the data.

TODOs:
  - [ ] actually use years on the client side, to future proof things (could wait till after initial release)
  - [x] server
    - [x] \*when querying initiatives by org, filter estimates included in response (see \* for related) #851
      - [x] think about this more, make sure it's not going to mess with/be messed with by Apollo's normalized caching
  - [ ] client subjects
    - [x] \*be more efficient when querying by dept (once server scopes estimates when querying by org, need to be able to merge in additional estimates data to initiative as additional queries made) #851
    - [x] ~populate `CovidEstimate` with rolled up data when fetching `CovidInitiative` for a given org~ #851
    - [ ] respect fiscal years
  - [ ] panels
    - [ ] I think the tables would be better as `(org or initiative) | ...est doc columns | cumulative authorities`... but dropping vote stat from them would mean something like an RPB table is necessary to still have that detail
    - [ ] gov tables are very long, could they be "top 10 depts", etc?
    - [ ] text is hard coded to current estimates docs, needs to be generalized. Maybe move list of tabled docs up from the overview so the above-tab text can just say "the documents listed below"
      - [ ] that might turn the "overview" tab in to a "vote stat" tab, which would leave more room for removing vote stat from the other tabs...
    - [ ] respect fiscal years
  - [ ] Going to either need to put the data in the report builder or give it a sub-app or something. Someone for sure will be asking to see all the data in full granularity all in one place, and linking to open data might not be satisfactory

**Comment by Stephen-ONeil** [comment]
Expecting these to all be superseded by changing plans (if not, they'll return in futures issues, I'm tracking them elsewhere for now).
